# Generated by Django 5.1.7 on 2026-03-10

from django.db import migrations


DEFAULT_INCOME_CATEGORIES = [
    "Salary",
    "Freelance",
    "Business",
    "Investments",
    "Bonus",
]

DEFAULT_EXPENSE_CATEGORIES = [
    "Housing",
    "Groceries",
    "Transportation",
    "Utilities",
    "Entertainment",
]


def seed_default_categories(apps, schema_editor):
    User = apps.get_model("pft", "User")
    Category = apps.get_model("pft", "Category")

    for user in User.objects.all().iterator():
        existing = {
            (category["type"], category["name"].strip().lower())
            for category in Category.objects.filter(user=user).values("type", "name")
        }

        categories_to_create = []

        for name in DEFAULT_INCOME_CATEGORIES:
            if ("income", name.lower()) not in existing:
                categories_to_create.append(
                    Category(name=name, type="income", user_id=user.id)
                )

        for name in DEFAULT_EXPENSE_CATEGORIES:
            if ("expense", name.lower()) not in existing:
                categories_to_create.append(
                    Category(name=name, type="expense", user_id=user.id)
                )

        if categories_to_create:
            Category.objects.bulk_create(categories_to_create)


class Migration(migrations.Migration):

    dependencies = [
        ("pft", "0003_remove_billreminder_user_remove_debtaccount_user_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_default_categories, migrations.RunPython.noop),
    ]
