# Generated by Codex on 2026-03-10

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models, transaction
from django.db.models import Q, Sum


def backfill_v1_to_v2(apps, schema_editor):
    User = apps.get_model("pft", "User")
    Category = apps.get_model("pft", "Category")
    Transaction = apps.get_model("pft", "Transaction")
    Budget = apps.get_model("pft", "Budget")

    BudgetFile = apps.get_model("pft", "BudgetFile")
    Account = apps.get_model("pft", "Account")
    CategoryGroupV2 = apps.get_model("pft", "CategoryGroupV2")
    CategoryV2 = apps.get_model("pft", "CategoryV2")
    LedgerTransaction = apps.get_model("pft", "LedgerTransaction")
    LedgerPosting = apps.get_model("pft", "LedgerPosting")
    BudgetMonth = apps.get_model("pft", "BudgetMonth")
    EnvelopeAssignment = apps.get_model("pft", "EnvelopeAssignment")

    for user in User.objects.all().iterator():
        with transaction.atomic():
            budget_file = (
                BudgetFile.objects.filter(user=user, is_default=True).order_by("id").first()
            )
            if not budget_file:
                budget_file = BudgetFile.objects.create(
                    user=user,
                    name="Primary Budget",
                    currency_code="USD",
                    is_default=True,
                )

            default_account = (
                Account.objects.filter(budget_file=budget_file).order_by("id").first()
            )
            if not default_account:
                default_account = Account.objects.create(
                    budget_file=budget_file,
                    name="Cash",
                    type="checking",
                    opening_balance=Decimal("0.00"),
                )

            income_group, _ = CategoryGroupV2.objects.get_or_create(
                budget_file=budget_file,
                name="Income",
                defaults={"sort_order": 0},
            )
            expense_group, _ = CategoryGroupV2.objects.get_or_create(
                budget_file=budget_file,
                name="Expenses",
                defaults={"sort_order": 1},
            )

            category_map = {}
            for category in Category.objects.filter(user=user).order_by("id"):
                kind = "income" if category.type == "income" else "expense"
                group = income_group if kind == "income" else expense_group
                category_v2, _ = CategoryV2.objects.get_or_create(
                    budget_file=budget_file,
                    name=category.name,
                    defaults={
                        "kind": kind,
                        "group": group,
                    },
                )
                category_map[category.id] = category_v2

            uncategorized_expense, _ = CategoryV2.objects.get_or_create(
                budget_file=budget_file,
                name="Uncategorized Expense",
                defaults={
                    "kind": "expense",
                    "group": expense_group,
                },
            )
            uncategorized_income, _ = CategoryV2.objects.get_or_create(
                budget_file=budget_file,
                name="Uncategorized Income",
                defaults={
                    "kind": "income",
                    "group": income_group,
                },
            )

            for tx in Transaction.objects.filter(user=user).order_by("id"):
                amount = Decimal(tx.amount)
                category_v2 = category_map.get(tx.category_id)
                if not category_v2:
                    category_v2 = (
                        uncategorized_income
                        if tx.type == "income"
                        else uncategorized_expense
                    )

                if tx.type == "income":
                    account_amount = abs(amount)
                    category_amount = -abs(amount)
                else:
                    account_amount = -abs(amount)
                    category_amount = abs(amount)

                ledger_tx = LedgerTransaction.objects.create(
                    budget_file=budget_file,
                    transaction_date=tx.transaction_date,
                    memo=tx.title,
                    source_type="manual",
                    cleared=False,
                    imported=False,
                    match_key=f"v1-{tx.id}",
                )
                LedgerPosting.objects.bulk_create(
                    [
                        LedgerPosting(
                            transaction=ledger_tx,
                            account=default_account,
                            amount=account_amount,
                            sort_order=0,
                        ),
                        LedgerPosting(
                            transaction=ledger_tx,
                            category=category_v2,
                            amount=category_amount,
                            sort_order=1,
                        ),
                    ]
                )

            for budget in Budget.objects.filter(user=user).order_by("id"):
                category_v2 = category_map.get(budget.category_id)
                if not category_v2:
                    continue

                budget_month, _ = BudgetMonth.objects.get_or_create(
                    budget_file=budget_file,
                    year=budget.year,
                    month=budget.month,
                    defaults={
                        "mode": "envelope",
                    },
                )
                EnvelopeAssignment.objects.update_or_create(
                    budget_month=budget_month,
                    category=category_v2,
                    defaults={
                        "assigned_amount": budget.amount_limit,
                        "carryover_amount": Decimal("0.00"),
                        "goal_type": "none",
                        "priority": 100,
                    },
                )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("pft", "0004_seed_default_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("currency_code", models.CharField(default="USD", max_length=3)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.AddConstraint(
            model_name="budgetfile",
            constraint=models.UniqueConstraint(
                condition=Q(("is_default", True)),
                fields=("user",),
                name="unique_default_budget_file_per_user",
            ),
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("checking", "Checking"),
                            ("savings", "Savings"),
                            ("cash", "Cash"),
                            ("credit", "Credit Card"),
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                        ],
                        default="checking",
                        max_length=16,
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="pft.budgetfile",
                    ),
                ),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("budget_file", "name"),
                name="unique_account_name_per_budget_file",
            ),
        ),
        migrations.CreateModel(
            name="CategoryGroupV2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_groups",
                        to="pft.budgetfile",
                    ),
                ),
            ],
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.AddConstraint(
            model_name="categorygroupv2",
            constraint=models.UniqueConstraint(
                fields=("budget_file", "name"),
                name="unique_category_group_name_per_budget_file",
            ),
        ),
        migrations.CreateModel(
            name="CategoryV2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        default="expense",
                        max_length=12,
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("notes_md", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories_v2",
                        to="pft.budgetfile",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="categories",
                        to="pft.categorygroupv2",
                    ),
                ),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.AddConstraint(
            model_name="categoryv2",
            constraint=models.UniqueConstraint(
                fields=("budget_file", "name"),
                name="unique_category_v2_name_per_budget_file",
            ),
        ),
        migrations.CreateModel(
            name="Payee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payees",
                        to="pft.budgetfile",
                    ),
                ),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.AddConstraint(
            model_name="payee",
            constraint=models.UniqueConstraint(
                fields=("budget_file", "name"),
                name="unique_payee_name_per_budget_file",
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="pft.budgetfile",
                    ),
                ),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("budget_file", "name"),
                name="unique_tag_name_per_budget_file",
            ),
        ),
        migrations.CreateModel(
            name="LedgerTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateField()),
                ("memo", models.TextField(blank=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("import", "Import"),
                            ("rule", "Rule"),
                            ("scheduled", "Scheduled"),
                            ("transfer", "Transfer"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("cleared", models.BooleanField(default=False)),
                ("imported", models.BooleanField(default=False)),
                ("match_key", models.CharField(blank=True, db_index=True, max_length=255)),
                ("transfer_group", models.UUIDField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_transactions",
                        to="pft.budgetfile",
                    ),
                ),
                (
                    "payee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_transactions",
                        to="pft.payee",
                    ),
                ),
            ],
            options={"ordering": ["-transaction_date", "-id"]},
        ),
        migrations.CreateModel(
            name="BudgetMonth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                (
                    "mode",
                    models.CharField(
                        choices=[("envelope", "Envelope"), ("traditional", "Traditional")],
                        default="envelope",
                        max_length=16,
                    ),
                ),
                ("notes_md", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_months",
                        to="pft.budgetfile",
                    ),
                ),
            ],
            options={"ordering": ["-year", "-month", "-id"]},
        ),
        migrations.AddConstraint(
            model_name="budgetmonth",
            constraint=models.UniqueConstraint(
                fields=("budget_file", "year", "month"),
                name="unique_budget_month_per_budget_file",
            ),
        ),
        migrations.CreateModel(
            name="ScheduledTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField()),
                ("next_run_date", models.DateField()),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("custom", "Custom"),
                        ],
                        default="monthly",
                        max_length=12,
                    ),
                ),
                ("interval", models.PositiveIntegerField(default=1)),
                ("transaction_template", models.JSONField(blank=True, default=dict)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_transactions",
                        to="pft.budgetfile",
                    ),
                ),
            ],
            options={"ordering": ["next_run_date", "id"]},
        ),
        migrations.CreateModel(
            name="TransactionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("actions", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_rules",
                        to="pft.budgetfile",
                    ),
                ),
            ],
            options={"ordering": ["priority", "id"]},
        ),
        migrations.CreateModel(
            name="SavedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("net_worth", "Net Worth"),
                            ("cash_flow", "Cash Flow"),
                            ("spending", "Spending Trends"),
                            ("custom", "Custom"),
                        ],
                        max_length=16,
                    ),
                ),
                ("definition", models.JSONField(blank=True, default=dict)),
                ("pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_reports",
                        to="pft.budgetfile",
                    ),
                ),
            ],
            options={"ordering": ["-updated_at", "-id"]},
        ),
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("csv", "CSV"), ("json", "JSON"), ("xlsx", "XLSX")],
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("content_text", models.TextField(blank=True)),
                ("content_b64", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "budget_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to="pft.budgetfile",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="EncryptedBackupBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bundle_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("encryption_algorithm", models.CharField(default="AES-GCM", max_length=32)),
                ("key_derivation", models.CharField(default="PBKDF2", max_length=32)),
                ("salt", models.TextField()),
                ("nonce", models.TextField()),
                ("ciphertext", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "budget_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encrypted_backups",
                        to="pft.budgetfile",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encrypted_backups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("ofx", "OFX"),
                            ("qfx", "QFX"),
                            ("qif", "QIF"),
                            ("camt053", "CAMT.053"),
                            ("ynab4", "YNAB4"),
                            ("nynab", "nYNAB"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("previewed", "Previewed"),
                            ("importing", "Importing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=12,
                    ),
                ),
                ("source_filename", models.CharField(blank=True, max_length=255)),
                ("source_payload", models.TextField(blank=True)),
                ("preview_summary", models.JSONField(blank=True, default=dict)),
                ("mapping", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to="pft.budgetfile",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="LedgerPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("memo", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_postings",
                        to="pft.account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_postings",
                        to="pft.categoryv2",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postings",
                        to="pft.ledgertransaction",
                    ),
                ),
            ],
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.AddConstraint(
            model_name="ledgerposting",
            constraint=models.CheckConstraint(
                check=(
                    (Q(("account__isnull", False), ("category__isnull", True)))
                    | (Q(("account__isnull", True), ("category__isnull", False)))
                ),
                name="ledger_posting_exactly_one_target",
            ),
        ),
        migrations.CreateModel(
            name="LedgerTransactionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_links",
                        to="pft.tag",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_links",
                        to="pft.ledgertransaction",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="ledgertransactiontag",
            constraint=models.UniqueConstraint(
                fields=("transaction", "tag"),
                name="unique_tag_per_ledger_transaction",
            ),
        ),
        migrations.AddField(
            model_name="ledgertransaction",
            name="tags",
            field=models.ManyToManyField(blank=True, through="pft.LedgerTransactionTag", to="pft.tag"),
        ),
        migrations.CreateModel(
            name="EnvelopeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "carryover_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("target_balance", "Target Balance"),
                            ("monthly_contribution", "Monthly Contribution"),
                            ("percent_income", "Percent Income"),
                            ("remainder", "Remainder"),
                            ("by_date", "By Date"),
                            ("by_schedule", "By Schedule"),
                        ],
                        default="none",
                        max_length=24,
                    ),
                ),
                (
                    "goal_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("goal_date", models.DateField(blank=True, null=True)),
                ("goal_schedule", models.CharField(blank=True, max_length=200)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("notes_md", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget_month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="pft.budgetmonth",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envelope_assignments",
                        to="pft.categoryv2",
                    ),
                ),
            ],
            options={"ordering": ["priority", "id"]},
        ),
        migrations.AddConstraint(
            model_name="envelopeassignment",
            constraint=models.UniqueConstraint(
                fields=("budget_month", "category"),
                name="unique_envelope_assignment_per_month_category",
            ),
        ),
        migrations.CreateModel(
            name="TransactionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("bulk_update", "Bulk update"),
                            ("import", "Import"),
                            ("reconcile", "Reconcile"),
                        ],
                        max_length=24,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "budget_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_events",
                        to="pft.budgetfile",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="pft.ledgertransaction",
                    ),
                ),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.RunPython(backfill_v1_to_v2, reverse_code=noop_reverse),
    ]
