# Generated by Django 5.1.7 on 2026-08-13 03:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models




def backfill_personal_organizations(apps, schema_editor):
    """Every existing user gets a personal org; their budget files join it."""
    Organization = apps.get_model("pft", "Organization")
    Membership = apps.get_model("pft", "Membership")
    BudgetFile = apps.get_model("pft", "BudgetFile")
    User = apps.get_model("pft", "User")

    for user in User.objects.all().iterator():
        organization = Organization.objects.create(
            name=f"{user.email}'s space", personal=True
        )
        Membership.objects.create(organization=organization, user=user, role="owner")
        BudgetFile.objects.filter(user=user).update(organization=organization)


def unlink_personal_organizations(apps, schema_editor):
    # Reverse: rows survive; the FK column drop in the schema reversal handles it.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pft', '0006_enforce_ledger_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('personal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='budgetfile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_files', to='pft.organization'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='pft.organization')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='unique_membership')],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=12)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='pft.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('accepted_at__isnull', True)), fields=('organization', 'email'), name='unique_pending_invitation')],
            },
        ),
        migrations.RunPython(backfill_personal_organizations, unlink_personal_organizations),
    ]
