# Generated by Django 5.1.7 on 2026-08-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pft', '0007_organization_budgetfile_organization_membership_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budgetfile',
            name='unique_default_budget_file_per_user',
        ),
        migrations.AddConstraint(
            model_name='budgetfile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'organization'), name='unique_default_budget_file_per_user_org'),
        ),
    ]
