# Generated by Django 5.1.7 on 2026-08-24 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pft', '0009_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('budget_threshold', 'Budget threshold'), ('scheduled_reminder', 'Scheduled reminder'), ('weekly_digest', 'Weekly digest')], max_length=24)),
                ('dedupe_key', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'dedupe_key'), name='unique_notification_per_user_kind_dedupe_key')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=False)),
                ('ntfy_enabled', models.BooleanField(default=False)),
                ('ntfy_server_url', models.URLField(default='https://ntfy.sh', max_length=255)),
                ('ntfy_topic', models.CharField(blank=True, max_length=120)),
                ('webhook_enabled', models.BooleanField(default=False)),
                ('webhook_url', models.URLField(blank=True, max_length=500)),
                ('budget_alerts_enabled', models.BooleanField(default=True)),
                ('budget_alert_threshold', models.PositiveSmallIntegerField(default=90)),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('reminder_days_before', models.PositiveSmallIntegerField(default=1)),
                ('weekly_digest_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('budget_alert_threshold__gte', 1), ('budget_alert_threshold__lte', 100)), name='notification_budget_alert_threshold_range'), models.CheckConstraint(condition=models.Q(('reminder_days_before__gte', 0), ('reminder_days_before__lte', 30)), name='notification_reminder_days_before_range')],
            },
        ),
    ]
