# Generated by Django 5.1.7 on 2026-08-24 09:30

import django.db.models.deletion
from django.db import migrations, models


def backfill_account_currency(apps, schema_editor):
    """Every existing account explicitly gets its budget file's currency
    instead of staying blank. New accounts get this from AccountSerializer.
    validate() at create time; this is only for rows that predate the field -
    see Account.currency_code's docstring in models.py.
    """
    Account = apps.get_model("pft", "Account")
    accounts = Account.objects.select_related("budget_file").exclude(
        budget_file__isnull=True
    )
    for account in accounts.iterator():
        account.currency_code = account.budget_file.currency_code
        account.save(update_fields=["currency_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('pft', '0010_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency_code',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.RunPython(backfill_account_currency, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='importjob',
            name='format',
            field=models.CharField(choices=[('csv', 'CSV'), ('ofx', 'OFX'), ('qfx', 'QFX'), ('qif', 'QIF'), ('camt053', 'CAMT.053'), ('ynab4', 'YNAB4'), ('nynab', 'nYNAB'), ('firefly3', 'Firefly III'), ('actual', 'Actual Budget')], max_length=12),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('import', 'Import'), ('rule', 'Rule'), ('scheduled', 'Scheduled'), ('transfer', 'Transfer'), ('sync', 'Bank Sync')], default='manual', max_length=16),
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateField(db_index=True)),
                ('currency_code', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-rate_date'],
                'indexes': [models.Index(fields=['currency_code', '-rate_date'], name='pft_fxrate_currenc_d89132_idx')],
                'constraints': [models.UniqueConstraint(fields=('rate_date', 'currency_code'), name='unique_fx_rate_per_day_currency')],
            },
        ),
        migrations.CreateModel(
            name='SyncConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gocardless', 'GoCardless Bank Account Data'), ('simplefin', 'SimpleFIN Bridge')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('error', 'Error'), ('revoked', 'Revoked')], default='pending', max_length=12)),
                ('institution_name', models.CharField(blank=True, max_length=160)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('secret_data', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_connections', to='pft.budgetfile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SyncConnectionAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_account_id', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=160)),
                ('currency_code', models.CharField(blank=True, max_length=3)),
                ('iban', models.CharField(blank=True, max_length=64)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_links', to='pft.account')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to='pft.syncconnection')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('connection', 'external_account_id'), name='unique_external_account_per_connection')],
            },
        ),
    ]
