# Generated by Django 5.1.7 on 2026-08-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pft', '0011_bank_sync_and_multi_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgertransaction',
            name='transaction_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='report_type',
            field=models.CharField(choices=[('net_worth', 'Net Worth'), ('cash_flow', 'Cash Flow'), ('spending', 'Spending Trends'), ('custom', 'Custom'), ('net_worth_series', 'Net Worth Over Time'), ('cash_flow_sankey', 'Cash Flow Sankey')], max_length=32),
        ),
    ]
