# Generated by Django 5.1.7 on 2026-08-25 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pft', '0013_alter_savedreport_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to='pft.account')),
                ('budget_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to='pft.budgetfile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('budget_file', 'name'), name='unique_savings_goal_name_per_budget_file')],
            },
        ),
    ]
