# Generated by Django 5.1.7 on 2026-08-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pft', '0014_savingsgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual percentage rate, e.g. 19.99 for 19.99% APR.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='minimum_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='report_type',
            field=models.CharField(choices=[('net_worth', 'Net Worth'), ('cash_flow', 'Cash Flow'), ('spending', 'Spending Trends'), ('custom', 'Custom'), ('net_worth_series', 'Net Worth Over Time'), ('cash_flow_sankey', 'Cash Flow Sankey'), ('subscriptions', 'Subscriptions'), ('debt_payoff', 'Debt Payoff')], max_length=32),
        ),
    ]
