# Generated by Django 5.1.7 on 2026-08-25 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pft', '0015_account_interest_rate_account_minimum_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICategorizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('provider', models.CharField(choices=[('openai_compatible', 'OpenAI-compatible (bring your own key)'), ('ollama', 'Ollama (local)')], default='openai_compatible', max_length=20)),
                ('base_url', models.CharField(blank=True, max_length=500)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('encrypted_api_key', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_categorization_settings', to='pft.budgetfile')),
            ],
        ),
    ]
